services:
  app:
    image: ghcr.io/taramid/wisdom:latest
    container_name: wisdom-app-1
    restart: unless-stopped

    ports:
      - "8001:80"

    env_file:
      - .env

    environment:
      - APP_ENV=prod
#      - SERVER_NAME=:80   # for Caddy
